namespace:
  name: staging

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.18.0"

service:
  type: ClusterIP
  port: 8111

resources:
  requests:
    cpu: 50m
    memory: 128Mi

configmap:
  data: "version: 1.18.0"

